name: heroku_deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "peaceful-sea-41551"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://peaceful-sea-41551.herokuapp.com/"
          usedocker: true
          delay: 60
          rollbackonhealthcheckfailed: true
        env:
          HD_API_KEY: ${{secrets.MAPS_API_KEY}} # Docker env must start with HD for Heroku, HD_ will be removed
